export interface Metric {
  timestamp: number
  value: number
  labels: Record<string, string>
  service: string
  host: string
}

export interface Anomaly {
  id: string
  timestamp: number
  metric: string
  expectedValue: number
  actualValue: number
  severity: "low" | "medium" | "high" | "critical"
  confidence: number
  service: string
  host: string
  autoRemediated: boolean
  remediationAction?: string
}

export interface LogEntry {
  timestamp: number
  level: "info" | "warn" | "error" | "critical"
  message: string
  service: string
  host: string
  metadata: Record<string, any>
}

export interface Incident {
  id: string
  timestamp: number
  title: string
  description: string
  severity: "low" | "medium" | "high" | "critical"
  status: "open" | "investigating" | "resolved" | "auto-resolved"
  affectedServices: string[]
  rootCause?: string
  remediation?: RemediationAction
  mttr?: number // Mean Time To Resolution in seconds
  predictedBy?: string // ML model that predicted this
}

export interface RemediationAction {
  id: string
  incidentId: string
  action: string
  type: "restart" | "scale" | "failover" | "config-change" | "custom"
  status: "pending" | "in-progress" | "completed" | "failed"
  executedAt?: number
  completedAt?: number
  result?: string
  automated: boolean
}

export interface PredictionModel {
  id: string
  name: string
  type: "time-series" | "classification" | "regression" | "clustering"
  accuracy: number
  lastTrained: number
  predictions: number
  prevented: number
}

export interface HealthScore {
  overall: number
  cpu: number
  memory: number
  disk: number
  network: number
  services: Record<string, number>
  timestamp: number
}

export interface CostAnomaly {
  id: string
  timestamp: number
  service: string
  cloudProvider: "aws" | "gcp" | "azure" | "linode"
  expectedCost: number
  actualCost: number
  costIncrease: number // percentage
  linkedToPerformanceIssue: boolean
  performanceIssueId?: string
  severity: "low" | "medium" | "high" | "critical"
}

export interface NaturalLanguageQuery {
  query: string
  timestamp: number
  results: {
    incidents: Incident[]
    anomalies: Anomaly[]
    insights: string[]
    timeRange: { start: number; end: number }
  }
}

export interface BlastRadiusAnalysis {
  changeId: string
  affectedServices: string[]
  riskScore: number // 0-100
  impactedUsers: number
  dependencyChain: string[]
  recommendations: string[]
  rollbackPlan: string
}

export interface AutoGeneratedRunbook {
  id: string
  title: string
  triggeredBy: string // incident pattern
  steps: RunbookStep[]
  successRate: number
  timesExecuted: number
  avgResolutionTime: number
  lastUpdated: number
}

export interface RunbookStep {
  order: number
  action: string
  command?: string
  expectedOutcome: string
  failureHandling: string
}

export interface DeveloperExperienceMetric {
  timestamp: number
  buildTime: number
  deploymentFrequency: number
  failedDeployments: number
  incidentsDuringDeploy: number
  developerProductivity: number // 0-100 score
  cicdHealth: number
}

export interface ComplianceDrift {
  id: string
  timestamp: number
  service: string
  baseline: string // compliance standard
  driftType: "security" | "configuration" | "access" | "encryption" | "logging"
  severity: "low" | "medium" | "high" | "critical"
  details: string
  autoRemediable: boolean
}

export interface TenantHealth {
  tenantId: string
  healthScore: number
  errorRate: number
  latency: number
  resourceUsage: number
  incidents: number
  trend: "improving" | "stable" | "degrading"
}

export interface ChaosRecommendation {
  id: string
  type: "latency" | "failure" | "resource-exhaustion" | "network-partition"
  targetService: string
  reasoning: string
  priority: "low" | "medium" | "high"
  estimatedImpact: string
  safeguards: string[]
}
