import type { Service } from "./types"

export const mockServices: Service[] = [
  {
    id: "1",
    name: "production-kafka-01",
    serviceType: "kafka",
    cloudProvider: "aws",
    size: "large",
    status: "running",
    region: "us-east-1",
    createdAt: new Date("2024-01-15"),
    config: {
      brokerCount: 7,
      instanceType: "m5.4xlarge",
      storageSize: 1000,
      replicationFactor: 3,
      minInSyncReplicas: 2,
      retentionHours: 720,
      enableEncryption: true,
      enableMonitoring: true,
    },
    metrics: {
      throughput: 450,
      messagesPerSecond: 125000,
      diskUsage: 65,
      cpuUsage: 42,
      memoryUsage: 68,
      activeConnections: 234,
    },
    cost: {
      hourly: 5.45,
      monthly: 3978.5,
    },
    terraformGenerated: true,
    deploymentId: "deploy-1705334400000",
  },
  {
    id: "2",
    name: "redis-cache-cluster",
    serviceType: "redis",
    cloudProvider: "gcp",
    size: "medium",
    status: "running",
    region: "us-central1",
    createdAt: new Date("2024-02-10"),
    config: {
      nodeCount: 6,
      clusterMode: true,
      storageSize: 100,
      maxMemoryPolicy: "allkeys-lru",
      persistenceEnabled: true,
      instanceType: "n2-standard-4",
      enableEncryption: true,
      enableMonitoring: true,
    },
    metrics: {
      diskUsage: 42,
      cpuUsage: 35,
      memoryUsage: 78,
      activeConnections: 512,
      requestsPerSecond: 45000,
      cacheHitRate: 94.5,
    },
    cost: {
      hourly: 1.2,
      monthly: 876.0,
    },
    terraformGenerated: true,
  },
  {
    id: "3",
    name: "mysql-master-slave",
    serviceType: "mysql",
    cloudProvider: "azure",
    size: "medium",
    status: "running",
    region: "eastus",
    createdAt: new Date("2024-01-20"),
    config: {
      mode: "orchestrated",
      masterCount: 1,
      slaveCount: 3,
      storageSize: 500,
      instanceType: "Standard_E4s_v3",
      enableEncryption: true,
      enableMonitoring: true,
      enableBackup: true,
      orchestration: {
        autoFailover: true,
        readReplicas: 3,
        backupSchedule: "0 2 * * *",
      },
    },
    metrics: {
      diskUsage: 58,
      cpuUsage: 48,
      memoryUsage: 62,
      activeConnections: 156,
      requestsPerSecond: 8500,
    },
    cost: {
      hourly: 1.0,
      monthly: 730.0,
    },
    terraformGenerated: true,
  },
  {
    id: "4",
    name: "elasticsearch-logs",
    serviceType: "elasticsearch",
    cloudProvider: "aws",
    size: "large",
    status: "running",
    region: "us-west-2",
    createdAt: new Date("2024-02-05"),
    config: {
      masterNodes: 3,
      dataNodes: 6,
      ingestNodes: 2,
      shardCount: 15,
      replicaCount: 2,
      storageSize: 1000,
      instanceType: "r5.2xlarge",
      enableEncryption: true,
      enableMonitoring: true,
    },
    metrics: {
      diskUsage: 72,
      cpuUsage: 55,
      memoryUsage: 81,
      activeConnections: 89,
      requestsPerSecond: 12000,
    },
    cost: {
      hourly: 5.8,
      monthly: 4234.0,
    },
    terraformGenerated: true,
  },
  {
    id: "5",
    name: "mongodb-analytics",
    serviceType: "mongodb",
    cloudProvider: "linode",
    size: "medium",
    status: "running",
    region: "us-east",
    createdAt: new Date("2024-03-01"),
    config: {
      replicaSetMembers: 3,
      sharding: true,
      configServers: 3,
      mongosRouters: 2,
      storageSize: 500,
      instanceType: "g6-highmem-4",
      enableEncryption: true,
      enableMonitoring: true,
    },
    metrics: {
      diskUsage: 45,
      cpuUsage: 38,
      memoryUsage: 65,
      activeConnections: 234,
      requestsPerSecond: 3500,
    },
    cost: {
      hourly: 0.72,
      monthly: 525.6,
    },
    terraformGenerated: true,
  },
  {
    id: "6",
    name: "nat-gateway-vpc",
    serviceType: "nat-gateway",
    cloudProvider: "aws",
    size: "small",
    status: "running",
    region: "us-east-1",
    createdAt: new Date("2024-02-20"),
    config: {
      publicSubnets: 2,
      privateSubnets: 4,
      storageSize: 50,
      enableIptables: true,
      firewallRules: [
        {
          id: "1",
          name: "Allow HTTP",
          protocol: "tcp",
          port: "80",
          sourceIP: "0.0.0.0/0",
          action: "allow",
        },
        {
          id: "2",
          name: "Allow HTTPS",
          protocol: "tcp",
          port: "443",
          sourceIP: "0.0.0.0/0",
          action: "allow",
        },
        {
          id: "3",
          name: "Allow SSH",
          protocol: "tcp",
          port: "22",
          sourceIP: "10.0.0.0/8",
          action: "allow",
        },
      ],
      instanceType: "t3.medium",
      enableEncryption: false,
      enableMonitoring: true,
    },
    metrics: {
      diskUsage: 15,
      cpuUsage: 12,
      memoryUsage: 25,
      activeConnections: 89,
    },
    cost: {
      hourly: 0.15,
      monthly: 109.5,
    },
    terraformGenerated: true,
  },
  {
    id: "7",
    name: "dev-kafka-cluster",
    serviceType: "kafka",
    cloudProvider: "gcp",
    size: "small",
    status: "stopped",
    region: "us-west1",
    createdAt: new Date("2024-03-10"),
    config: {
      brokerCount: 3,
      instanceType: "n2-standard-2",
      storageSize: 100,
      replicationFactor: 2,
      minInSyncReplicas: 1,
      retentionHours: 168,
      enableEncryption: false,
      enableMonitoring: true,
    },
    cost: {
      hourly: 0.32,
      monthly: 233.6,
    },
    terraformGenerated: true,
  },
]

// Legacy export for backward compatibility
export const mockClusters = mockServices.filter((s) => s.serviceType === "kafka")
